export class BusinessDetails {
	public userId?: string;
	public businessId?: string;
	public businessCode?: string;
	public businessName?: string;
	public businessDescription?: string;
	public businessLogo?: string;
	public businessWebsite?: string;
	public businessIncorporationDate?: string;
	public businessOfficePhone?: string;
	public businessTurnover?: string;
	public businessEmployeeStrength?: string;
	public businessOfficeType?: string;
	public businessOfficeSpace?: string;
	public businessSubscriptionDate?: string;
	public businessRenewalFrequency?: string;
	public businessRenewalStatus?: string;
	public businessLastRenewalDate?: string;
	public businessVerifiedBy?: string;
	public businessVerifiedDate?: string;
	public businessRejectionStatus?: string;
	public businessRejectionReason?: string;
	public currentBadge?: string;
	public isBlacklisted?: string;
	public blacklistedDate?: string;
	public blacklistedReason?: string;
	public panNo?: string;
	public gstNo?: string;
}
